### ISSUE TITLE
Use experimental CF CRs to drive workload staging

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-crd-explorations#6]
## Background

We want to get a better understanding of what building a CF v3 API that is backed by custom resources actually looks like.

Consider making an app we can use to demo and experiment with. Other teams have found [spring-pet-clinic](https://github.com/spring-projects/spring-petclinic) to be a good candidate since it is Java (what our customers use!) and relies on a MySQL database.

Using the CRDs (probably Package, Build, Droplet) we created in #1. We should build some experimental controllers to reconcile these CRs and orchestrate staging with [kpack](https://github.com/pivotal/kpack). Manually create a single-layer OCI image containing the Spring Petclinic source to use as a `kpack` source for this story and set it on the `Package`.

The goal of this spike is to answer the following questions:
 * Are these the right CRDs? Are they missing anything? Can anything be simplified?
 * Gain familiarity with kpack and the app staging flow
 * Are these CRDs too tightly coupled to kpack or are they general enough to work for other staging mechanisms (e.g. Tekton)

## Deliverable
 * A set of experimental controllers
 * Example custom resources to deploy the sample app
 * Keep a journal of what was difficult, what was easy, etc.
----

## Dev Notes
 * Refer to [the bottom part of this Miro board frame](https://miro.com/app/board/o9J_lFiI8CU=/?moveToWidget=3074457358340699913&cot=10) for inspiration.
 * Prior art from capi-k8s-release: https://github.com/cloudfoundry/capi-k8s-release/tree/main/src/cf-api-controllers/controllers. See the Build and Image controllers
* Refer to #3 for an example of controllers we've built for **running** apps

### Dev Provided Acceptance Steps
_**Fill me in**_

**Comment by matt-royal** [comment]
Some questions that @gnovv and I asked @tcdowney as part of this story:

## Where do we want to store the source image location information?
Let's move it to the Package spec under `source` and copy the format that kpack uses (https://github.com/pivotal/kpack/blob/main/docs/image.md#source-configuration). This applies for docker Packages as well. This will allow us to support additional types of source providers in the future (e.g. git, blob) whether or not kpack is the image building backend.

## How/When does CF create Droplets?
In short, Droplets are created automatically when a Build succeeds. In this context, we can have the BuildController create the Droplet automatically to replicate that behavior.

## In which namespace should we place the kpack Image and/or Build resources?
Let's not copy what cf-for-k8s does (i.e. place Image and Build resources in a single dedicated namespace for all apps). Instead, let's place the kpack resources in the same namespace as the CF Build custom resource.

## Note from Tim
We should design the Custom resources to be flexible and allow the use of other build systems besides kpack. If we encounter anywhere where we've assumed kpack, we should change the design to be more flexible.

**Comment by matt-royal** [comment]
## Open question: How do we want to handle the Package checksum now?

The CRD exploration had it as a status field. This would require that the Package controller to pull the image, check sum it, and then store that information on the status. It's also possible that the source can be corrupted or modified between when the Package is created and the checksum is calculated by the Package controller. *For this reason, we think the checksum should be part of the Package spec*.

Follow up: [ ] Decide how to represent the checksum on the Package object. If it's on the spec, what should the field be? How should we handle docker packages?

**Comment by tcdowney** [comment]
Regarding the Package checksum. We're going to forgo storing it on the `Package` CR for now. If users want a more deterministic `source` they can provide the image digest form of the image reference (e.g. `registry.example.com/my-image@sha256:c17889a3d84cabc22dbd7c5e960316c0aa1f6dc09d7328acc7953a542d67898d`) instead of a tag. The CF API Shim can always provide this form of the image reference when handling a `cf push`-ed application source. For users working with the `Package` CR directly it is up to them what form of reference they want to provide.

In terms of the CF API we can set the checksum fields to `null`. IMO the primary value of this checksum was for the clients to be able to verify the integrity of Packages retrieved via the [download Package bits endpoint](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#download-package-bits) which doesn't make much sense in this new world anyway where Packages point at OCI images instead of zip files in a blobstore.

**Comment by gnovv** [comment]
Paired w/ @tcdowney on this.

Main takeaway is that we need both a cf build reconciler and a kpack build to cf build reconciler.

We have mapped out the logic in the comments of this commit:
https://github.com/cloudfoundry/cf-crd-explorations/blob/e88608b9c9090a73ab4da85d02b0537a2f72f6b1/controllers/build_controller.go#L94

```
// KpackBuildCFBuildReconciler flow:
// watch kpack builds
// see kpack build is in terminal state
// update status of associated build

// buildpack Build Status
// created(staging)
//		-> build reconciler makes kpack image(still staging)
//			-> kpack image makes kpack build(still staging)
//				-> kpack build completes, kpack build reconciler updates build status (staged/failed)
// 					-> build reconciler creates droplet if state == staged

// docker Build Status
// created(staging)
//		-> build reconciler just changes status (staging->staged) and exits
//			-> build reconciler creates droplet if state == staged
```

**Comment by gnovv** [comment]
Open questions after 6/28/21
How do we communicate between the kpack build CR to our cf build CR?
Our initial idea was that we would create a custom reconciler to notice when the kpack build finishes and then it would modify the status of our cf build CR appropriately. This is still our plan, but we are unsure as to the exact mechanism.

We are using Build.Status.Conditions.Succeeded: `Unknown` to indicate a staging state.
Should the kpack-to-cf-build controller change that state directly to `True` to indicate a successful build, or should it add a separate condition to the cf Build CR? I am leaning to the latter, but we want to see what the standard is.

**Comment by tcdowney** [comment]
### Open question regarding concurrent Builds(6/28/21)

In CF for VMs and CF for K8s the CF API restricts apps such that they can only have one CF Build in flight (in the `STAGING` state) at a time. This is important in CF for K8s because we have a single kpack `Image` for the entire app that has [labels referring to a specific CF Droplet/Build](https://github.com/cloudfoundry/cloud_controller_ng/blob/2801afdc074272c20fcd3e23cfbb290cd52e1c2d/lib/cloud_controller/kpack/stager.rb#L58-L59).

These labels are used by the Build and Image controllers in capi-k8s-release so that it knows what resources on the CF API it should update when a kpack `Build` finishes.

In our new Build reconciler we need to make a choice. Do we continue creating a single kpack `Image` per app and have all Builds try to discover and update that `Image`? If we do this we will need to restrict concurrent Builds so that only one can be "in flight", otherwise they will interfere with each other. We will also need to figure out some sort of time-to-live/expiration for CF Builds so that the system doesn't get stuck if we do restrict ourselves here.

We could also change the model such that every new CF Build results in a new kpack `Image`. This would allow us to support concurrent CF Builds, but I'm not sure if there is some nuance that makes having multiple kpack `Image`s for an app bad. Does anyone remember why we have a single one in cf-for-k8s? @matt-royal @piyalibanerjee

**Comment by tcdowney** [comment]
We discussed the questions above as a team. There were shortcomings with the single kpack Image per App approach that cf-for-k8s took, namely it resulted in preventing developers from having concurrent Builds for an app. It also had an issue where the kpack Image's source would be updated to refer to the CF Package associated with the latest Build and that this would not necessarily match the Package associated with the App's current Droplet. This could cause stack updates to fail to produce the expected images for the app.

We decided that it is fine for every CF Build to create a new kpack Image and that this would result in a more flexible / easier to understand design.

@gnovv and I drew up what the happy paths for this controller might look like in the diagram below:

![Build Controller diagram](https://user-images.githubusercontent.com/2096955/123880694-0d350680-d8f8-11eb-9dcb-7a96bb585bcc.jpg)

For now we are ignoring Buildpack/Stack updates that create new kpack Builds. We are planning on having a separate exploration to think more deeply on that problem, but don't expect it to require significant changes to this side of the design.

**Comment by tcdowney** [comment]
While working on the "CFKpackBuildController" yesterday I spent some time digging in to what the [capi-k8s-release Build Controller](https://github.com/cloudfoundry/capi-k8s-release/blob/70031e21debb91d97fefde7ef17c15cfb2494683/src/cf-api-controllers/controllers/build_controller.go) was doing since it is also reconciling kpack Builds. I had two interesting observations.

1. It was ignoring automatic stack update builds via a filter.
2. It was calling out to the image registry to fetch image metadata for the stage app image in order to get information about process types and start commands. It send this information back to Cloud Controller to include on the Droplet. I created a new spike story to consider/implement this: https://github.com/cloudfoundry/cf-crd-explorations/issues/15

**Comment by gnovv** [comment]
Short notes from 7/1/21
- Need to ask kpack team which secret is used between builder and source image
- For now when you edit the cf build after completion, it will not update
- We should probably clean up kpack images with a Droplet finalizer

**Comment by Birdrock** [comment]
# Acceptance Steps

1. Get a cluster....somehow.
2. Install [Kpack](https://github.com/pivotal/kpack/releases/tag/v0.3.1)
3. Create kpack registry credentials `kubectl create secret docker-registry kpack-registry-credentials     --docker-username="_json_key"     --docker-password="$(cat <path-to-json-key>)"     --docker-server=gcr.io    --namespace default`
4. Install Kpack CRs `kubectl apply -f config/samples/kpack/serviceaccount.yaml -f config/samples/kpack/stack.yaml -f config/samples/kpack/store.yaml -f config/samples/kpack/builder.yaml`
5. Set env `export REGISTRY_TAG_BASE="gcr.io/<registry>/<repository-root>/<repository-name>"`
6. Install CF CRDs `make install`
7. Run controller `make run`
8. Apply CF CRs for app, bits_package, build. `kubectl apply -f config/samples/cf-crds/apps_v1alpha1_app.yaml -f config/samples/cf-crds/package/apps_v1alpha1_bits_package.yaml -f config/samples/cf-crds/apps_v1alpha1_build.yaml`

**Comment by gnovv** [comment]
# Acceptance Steps

## Docker Flow
---
### Happy Path

1.  Obtain a K8s Cluster
2. Install CF CRDs `make install`
3. Run controller `make run`
4. Apply CF CRs for app, docker_package, docker build.
`kubectl apply -f config/samples/cf-crds/apps_v1alpha1_app.yaml -f config/samples/cf-crds/package/apps_v1alpha1_docker_package.yaml -f config/samples/cf-crds/apps_v1alpha1_docker_build.yaml`

- Observe the status of the Build CR get updated `kubectl get builds docker-build-guid -o yaml` and confirm the following:
```
status:
  conditions:
  - lastTransitionTime: "2021-07-06T22:41:31Z"
    message: ""
    reason: Docker
    status: "True"
    type: Succeeded
  - lastTransitionTime: "2021-07-06T22:41:30Z"
    message: ""
    reason: Docker
    status: "False"
    type: Staging
  - lastTransitionTime: "2021-07-06T22:41:31Z"
    message: ""
    reason: Docker
    status: "True"
    type: Ready
```


### Failure Case

1. Perform the above steps
2. Modify the docker package with `kubectl edit package docker-package-guid` and blank out the image field like below:
```
spec:
  appRef:
    apiVersion: apps.cloudfoundry.org/v1alpha1
    kind: App
    name: my-app-guid
  source:
    registry:
      image: ""
      imagePullSecrets:
      - name: optional
```
3. Delete the build with `kubectl delete build docker-build-guid`
4. Recreate the build with `kubectl apply -f config/samples/cf-crds/apps_v1alpha1_docker_build.yaml`

- You should observe that the controller retries to make a droplet once every 10 seconds and the status will look like this:
`k get build docker-build-guid -o yaml`
```
status:
  conditions:
  - lastTransitionTime: "2021-07-06T22:50:34Z"
    message: packageRef package was empty
    reason: Docker
    status: Unknown
    type: Succeeded
  - lastTransitionTime: "2021-07-06T22:50:34Z"
    message: ""
    reason: NotReady
    status: Unknown
    type: Staging
  - lastTransitionTime: "2021-07-06T22:50:34Z"
    message: packageRef package was empty
    reason: Docker
    status: "False"
    type: Ready
```

5. Cleanup with `kubectl delete build docker-build-guid`

**Comment by gnovv** [comment]
App CR:
Should kpack lifecycle appear here and at Build CR level? If users will only interact with a desired app manifest, can one of these move to a status or tag?


Answer from Tim:
We should probably call it buildpack instead of kpack. Cloud Controller has the kpack type because it was a convenient way to fork the code. We don't have that restriction here and it will let us be more loosely coupled with whatever the buildpack runner is.

The ability to set the lifecycle (https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#lifecycles) on both the App and an individual Build is a feature of the V3 API. The one set on the App serves as a default so that folks don't need to provide it on every Build, but API clients are free to override it on any Build they want to create. This was done to provide flexibility -- one use case is to try out a new experimental buildpack for staging without "committing" to it for the App as a whole

Build CR:
It looks like the kpack build selector is not being used, should we remove it for now and add it back if/when we need it?
```
---
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: Build
metadata:
  name: build-guid
  labels:
    apps.cloudfoundry.org/appGuid: my-app-guid
    apps.cloudfoundry.org/packageGuid: kpack-package-guid
spec:
  # TODO: should this be buildpack?
  type: kpack
  packageRef:
    kind: Package
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: bits-package-guid
  appRef:
    kind: App
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: my-app-guid
  lifecycleData:
    # TODO: Write a story to think about how user-specified buildpacks work
    # cf-for-k8s makes a new builder per app
    buildpacks:
      - java_buildpack
    stack: cflinuxfs3
  # TODO: Do we even need these? Should we use them?
  kpackBuildSelector:
    matchLabels:
      apps.cloudfoundry.org/buildGuid: build-guid
  kpackImageTemplate:
    metadata:
      labels:
        apps.cloudfoundry.org/buildGuid: build-guid
```


Answer from Tim:

It looks like the kpack build selector is not being used, should we remove it for now and add it back if/when we need it?

I think we can remove it in its current form. One issue though is that there is an implicit coupling between the resources via their labels (apps.cloudfoundry.org/buildGuid) and that having a selector in the Spec can make this more explicit. We could refer to the selector itself instead of hardcoding that label -- but it might be YAGNI. @matt-royal and I were thinking about it that way when we originally proposed it in that initial CRD exploration, but I personally don't feel that strongly about it right now.
We definitely shouldn't have it mention kpack in the name though if we do want to keep using the selector approach.


Droplet CR:
Can we formalize the Droplet Migration/Promotion use case? Right now Droplets must reference an app and build- could we make those optional? Or do we expect users to just make Docker lifecycle type apps in the new environments?


Users of the CF APIs today are somewhat restricted in what they can do here and I think the Droplet CR provides more flexibility than what the CF for VMs API allows. Let's take a look at those endpoints.
There are a handful of APIs which allow for direct manipulation of droplets:
https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#create-a-droplet
https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#upload-droplet-bits
https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#download-droplet-bits
https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#copy-a-droplethttps://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#copy-a-droplet
The tl;dr of these is that.
Users can create a Droplet manually without a Build. That points to the Build field not being required on the Droplet. Additionally, Builds can be deleted (and are pruned frequently in CF for VMs) while the Droplet remains. So it's definitely valid for a Droplet to no longer refer to a CF Build. For a Droplet like this a user would have to use the "upload droplet bits" endpoint to power it themselves.
Downloading a droplet's bits probably doesn't apply in this new world.
Copying a Droplet from one App to another seems like something we'd definitely be able to support. Just copy the Droplet CR, change the App ref, and nil out the Build ref I think.
All of these endpoints require the Droplet belonging to an App. I think if we want to support free Droplets that is a product decision we could make, but if we're aiming for parity we do not need to.
So tl;dr is I think the Build ref could and should be optional, but the App ref should be required unless we want to support that use case. This means for Droplet migrations devs need to be aware of what App it goes with.
