### ISSUE TITLE
Explore: integrating `$KUBECONFIG`

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-crd-explorations#62]
# Background

## Authentication in EKS, AKS and GKE

Our previous explore have unveiled that the way different providers integrate with identity providers can be very different. In particular:

* Amazon EKS allows to configure a third-party OpenID Connect provider very easily. It's the only provider we've seen so far with full OIDC support. When this is not done, it integrates with Amazon's IAM using an OAuth 2.0-based system.
* Microsoft AKS is tightly integrated with Azure's authentication solution, Azure Active Directory, and doesn't allow to use third parties. While AAD tokens are valid OIDC tokens, it is not possible (or maybe just very hard / cumbersome) to authenticate to AAD using a standard OIDC flow. Instead, users are recommended to use the `az` CLI.
* Google GKE uses its own authentication solution which is not OIDC, but is still OAuth 2.0. Third parties are not supported. Users log in using the `gcloud` CLI (although standard OAuth 2.0 flow _might_ be supported?).

What all these providers have in common is the fact that they use `$KUBECONFIG` as their point of integration with the user. Instead of implementing standard OpenID Connect or OAuth flows for authentication and let the user handle their `$KUBECONFIG` (maybe via something like [`kubelogin`](https://github.com/int128/kubelogin)), they provide proprietary ways to generate the `$KUBECONFIG` directly.

## Ways of configuring authentication in `$KUBECONFIG`

User authentication configuration is stored in the [`AuthInfo`](https://pkg.go.dev/k8s.io/client-go@v0.21.3/tools/clientcmd/api#AuthInfo) struct. You can see there's different ways to do this:
* Client certificates, via the `client-certificate*` fields
* Bearer tokens via the `token*` fields
* Basic Auth via the `username` and `password` fields
* Custom plugins shipped with `client-go` via the `auth-provider` field
* Custom plugins as executables on the user's machine via the `exec` field

### `auth-provider` plugins

These are implementations of the [`AuthProvider`](https://pkg.go.dev/k8s.io/client-go@v0.21.3/rest#AuthProvider) interface, shipped with `client-go`. [AKS](https://pkg.go.dev/k8s.io/client-go@v0.21.3/plugin/pkg/client/auth/azure) and [GKE](https://pkg.go.dev/k8s.io/client-go@v0.21.3/plugin/pkg/client/auth/gcp) use these.

Curiously there's also an [OIDC](https://pkg.go.dev/k8s.io/client-go@v0.21.3/plugin/pkg/client/auth/oidc) implementation! It does *not* implement the OIDC/OAuth authentication flow, but expects the ID and refresh tokens as inputs and is capable of refreshing the token. For some reason `kubelogin` doesn't use this, but an `exec` plugin.

##### AKS

```yaml
auth-provider:
  config:
    apiserver-id: XXX
    client-id: XXX
    config-mode: '1'
```

##### GKE

```yaml
auth-provider:
  config:
    cmd-args: config config-helper --format=json
    cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
    expiry: "2021-07-28T14:38:50Z"
    expiry-key: '{.credential.token_expiry}'
    token-key: '{.credential.access_token}'
```

### `exec` plugins

These plugins can be implemented as executables which can be invoked by `client-go`/`kubectl` and return the necessary credentials via `stdout`. The output needs to deserialise to the [`ExecCredentials`](https://kubernetes.io/docs/reference/config-api/client-authentication.v1beta1/#client-authentication-k8s-io-v1beta1-ExecCredential) type, which can contain a token or a client certificate.

This is what EKS uses by default. `kubelogin` is an `exec` plugin too. AKS can be switched to this style of plugin via their [`kubelogin`](https://github.com/Azure/kubelogin) tool (not the same as `int128/kubelogin`), which migrates the users's `$KUBECONFIG` from using `auth-provider` to using `exec`.

##### EKS

```yaml
exec:
  apiVersion: client.authentication.k8s.io/v1alpha1
  args:
  - --region
  - us-west-2
  - eks
  - get-token
  - --cluster-name
  - cf-on-k8s-test
  command: aws
  env: null
  provideClusterInfo: false
```

##### `int128/kubelogin`

```yaml
exec:
  apiVersion: client.authentication.k8s.io/v1beta1
  command: kubectl
  args:
  - oidc-login
  - get-token
  - --oidc-issuer-url=XXX
  - --oidc-client-id=XXX
  - --oidc-client-secret=XXX
```

##### AKS + `Azure/kubelogin`

```yaml
exec:
  apiVersion: client.authentication.k8s.io/v1beta1
  args:
  - get-token
  - --server-id
  - XXX
  - --login
  - azurecli
  command: kubelogin
  env: null
  provideClusterInfo: false
```

# Question

* How feasible is it to integrate the `cf` CLI directly with `$KUBECONFIG`?
* Can we achieve a flow where the user, after logging in with the provider tool (`aws`/`az`/`gcloud`) can use the `cf` CLI straight away?
* If not, can we get away with a one-off setup command?
* Can we reuse code from [`client-go/plugin/pkg/client/auth`](https://pkg.go.dev/k8s.io/client-go@v0.21.3/plugin/pkg/client/auth)?
